version: "3.7"

services:
  server-name-example:
    image: project-name-example/server-name-example:latest
    container_name: server-name-example
    restart: always
    command: ["./serverNameExample", "-c", "/app/configs/serverNameExample.yml"]
    volumes:
      - $PWD/configs:/app/configs
# todo generate docker-compose.yml code for http or grpc here
# delete the templates code start
    ports:
      - "8080:8080"   # http port
      - "8282:8282"   # rpc port
      - "8283:8283"   # rpc metrics or pprof port
    # select health check according to service type (http or grpc)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]   # http health check, note: mirror must contain curl command
      #test: ["CMD", "grpc_health_probe", "-addr=localhost:8282"]    # grpc health check, note: the image must contain the grpc_health_probe command
# delete the templates code end
      interval: 10s         # interval time
      timeout: 5s           # timeout time
      retries: 3              # number of retries
      start_period: 10s  # how long after start-up does the check begin
